# ===============================
# SERVER CONFIGURATION
# ===============================
server:
  port: 8080

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://wtg-db:5432/wtg-db
    username: wtg-db
    password: wtg-db

  # ===============================
  # JPA & HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # ===============================
  # DATABASE INITIALIZATION
  # ===============================
  sql:
    init:
      mode: always

# ===============================
# LOGGING
# ===============================
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

# ===============================
# EXTERNAL SERVICES
# ===============================
stat-server:
  url: http://stat-server:9090