# ===============================
# SERVER CONFIGURATION
# ===============================
server:
  port: 9090

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stat-db:5432/stat-db
    username: stat-db
    password: stat-db

  # ===============================
  # JPA & HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # ===============================
  # DATABASE INITIALIZATION
  # ===============================
  sql:
    init:
      mode: always